# First we need to get the pgn file.
pgnname = input("Analyze which file? ")
pgnfile = open(pgnname, 'r')
pgn = pgnfile.read()

# Now we need to parse the pgn file for the evaluation scores.  The
# pgn files that this script is programed to parse are generated by
# the program Scid vs PC which encloses evaluation scores in curly
# brackets.
scores = []
evalstring = ""
recording = False

for char in pgn:
    if recording:
        if char in "1234567890.-+":
            evalstring += char
        else:
            recording = False
            scores.append(float(evalstring))
            evalstring = ""
    else:
        if char == "{":
            recording = True

# Now lets check to see if the parser is working.
ply = 0
for score in scores:
    ply += 1
    print(ply, score)
    
